version: 2.1 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point

    working_directory: ~ # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/openjdk:9-jdk # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run: mvn package # run the actual tests

      # Collect test reports
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/ \;
          when: always
      - store_test_results:
          path: ~/test-results

      # Upload code coverage
      - run: bash <(curl -s https://codecov.io/bash) -s ~
